{{- range $nodepools := .Values.nodePools }}
{{- $labels := .labels }}
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels: {{ toYaml $labels | nindent 4 }}
  name: {{ .name }}
spec:
  {{ if .disruption }}
  disruption:
    consolidationPolicy: {{ .disruption.consolidationPolicy }}
    expireAfter: {{ .disruption.expireAfter }}
    {{ if .disruption.budgets }}
    budgets: {{ toYaml .disruption.budgets | nindent 6 }}
    {{ end }}
  {{ end }}
  {{ if .limits }}
  limits: {{ toYaml .limits | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels: {{ toYaml $labels | nindent 6 }}
    spec:
      nodeClassRef:
        name: {{ .nodeClassRefName }}
      requirements: {{ toYaml .requirements | nindent 8 }}
       {{ if .startupTaints }}
      startupTaints: {{ toYaml .startupTaints | nindent 8 }}
      {{ end }}
       {{ if .startupTaints }}
      taints: {{ toYaml .taints | nindent 8 }}
      {{ end }}
  {{ if .weight }}
  weight: {{ .weight }}
  {{ end }}
{{- end }}