{{- range $nodepools := .Values.nodePools }}
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels: {{ toYaml $nodepools.labels | nindent 4 }}
  name: {{ $nodepools.name }}
spec:
  {{ if $nodepools.disruption }}
  disruption:
    consolidationPolicy: {{ $nodepools.disruption.consolidationPolicy }}
    expireAfter: {{ $nodepools.disruption.expireAfter }}
    {{ if $nodepools.disruption.budgets }}
    budgets: {{ toYaml $nodepools.disruption.budgets | nindent 6 }}
    {{ end }}
  {{ end }}
  {{ if $nodepools.limits }}
  limits: {{ toYaml $nodepools.limits | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels: {{ toYaml $nodepools.labels | nindent 6 }}
    spec:
      nodeClassRef:
        name: {{ $nodepools.nodeClassRefName }}
      requirements: {{ toYaml $nodepools.requirements | nindent 8 }}
      startupTaints: {{ toYaml $nodepools.startupTaints | nindent 8 }}
  weight: {{ $nodepools.weight }}
{{- end }}